version: "3"
services:
  producer:
    build: ./producer
    networks:
      - app-network
    ports:
      - "5000:5000"

  consumer:
    build: ./consumer
    networks:
      - app-network
    volumes:
      - logs:/data
    depends_on:
      - producer

networks:
  app-network:

volumes:
  logs:
